plugins {
  alias libs.plugins.gradleup.shadow
}

apply plugin: 'java'

repositories {
  mavenLocal()
  mavenCentral()
}

dependencies {
  implementation project(':core')
  implementation libs.jetty.server
  implementation libs.jetty.ee10.servlet
  implementation platform(libs.jackson.bom)
  implementation libs.jackson.databind
}

group 'com.schibsted.spt.data'
version '0.0.1'
project.description 'JSLT demo playground implementation'
